### PR TITLE
Add note on hyphenation

### PR DESCRIPTION
**Pull request by ACBSmith**
Added section on hyphenation, with example drawn from _A Doll's House_ based on notes from BTK

### CODE REVIEW

**Comment by ACBSmith** [comment]
I've add an initial page on music scoring, as well.

**Comment by vr8hub** [comment]
I'm going to have to do some research on GitHub; I know there's a way to request changes, but I can't find it right now and I don't have time to look further. So a comment it is. :)

We actually don't manually adjust hyphenation outside of modernize-spelling. Alex just addressed a similar question on the list a week or so ago.

For the music scores, it looks good, great job on the detail. I have been trying to keep a similar "tone" to the manual, so I'm avoiding "you" and "we" and such. (I'm still working on the SVG stuff, and I just had to change "our style manual" to "the SE Style manual" because my default is to write that way, too.) Would you make a pass through and adjust accordingly?

Thanks for starting this, Asher!

**Comment by ACBSmith** [comment]
Re: hyphens, I’m going off of this conversation I had with Bruce a couple weeks ago: https://github.com/ACBSmith/henrik-ibsen_a-dolls-house_r-farquharson-sharp/issues/1 <https://github.com/ACBSmith/henrik-ibsen_a-dolls-house_r-farquharson-sharp/issues/1> . He pointed out several places that hyphens needed to be modernised in ways that modernize-spelling couldn’t pick up, e.g. letter-box. 

Re: style, I was trying to mimic the style in the Shakespeare guide (https://standardebooks.org/contribute/how-tos/shakespeare <https://standardebooks.org/contribute/how-tos/shakespeare>), which uses “you” and the like. I agree about avoid “we” and “us,” but I’m struggling with how to find the balance for tone. I see what you mean about it mimicking the manual’s style, but also I think that a step-by-step guide should be slightly less strict about second person. The point of it is to tell people what to do, rather than how things are at the end of the process. I don’t know if that distinction makes any sense, though. I’ll take another pass through it, but I don’t think it should be entirely without second person or commands.

**Comment by ACBSmith** [comment]
I’ve stripped out first person, but left some second person. I stripped some out, but I felt that it had the tendency to get unwieldy sometimes.

I think, by the way, that comments are the easiest way to talk about this.

**Comment by ACBSmith** [comment]
Can you point me towards Alex talking about hyphenation? The only comments from him I can find in the last couple months are that it should be consistent and that we should defer to modernize-spelling even when it’s in a story title. No comments from him when producers have noted that they’ve changed hyphens in editorial commits.

**Comment by vr8hub** [comment]
It was in The Chessmen of Mars thread: "Typically we don't replace hyphens for spaces unless done
automatically by modernize-spelling."

The Shakespeare guide is the outlier at this point; for this, I'm following the manual, step-by-step guide, etc.

**Comment by ACBSmith** [comment]
OK, that makes sense in both regards. I'll have a look at adding some of those hyphenations to modernize-spelling's list and take a further pass at rewriting.

**Comment by ACBSmith** [comment]
Question regarding style: I've just gone to edit it to match the How-To guide, and found phrases in that like "you need to review your ebook by hand" and "we convert footnotes" in that document. I think there's a strong argument to be made that these guide pages shouldn't be restricted to the manual style. Thoughts?

**Pull request closed without merging**
